const items = [
   {
      id:0,
      name:"Blue Shirt",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },{
      id:1,
      name:"White Shirt",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:2,
      name:"Red Pant Circular Volarent",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:3,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:4,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:5,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:6,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:7,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:8,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:9,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:10,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:11,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:12,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:13,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:14,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
   {
      id:15,
      name:"Adidas",
      price:120,
      url:'https://source.unsplash.com/50x50/?man',
   },
]

export default items;